package dto;

import java.io.Serializable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library implements Serializable {

    private String name = "news";

    private int age = 26;


    public boolean someLibraryMethod() {
        return true;
    }


    /**
     * @return name
     */
    public String getName() {
        return name;
    }


    /**
     * @param name セットする name
     */
    public void setName(String name) {
        this.name = name;
    }


    /**
     * @return age
     */
    public int getAge() {
        return age;
    }


    /**
     * @param age セットする age
     */
    public void setAge(int age) {
        this.age = age;
    }



}
